# -*- coding: utf-8 -*-

# # 1.0 Tkr concept for Supplementary Figures 8 and 9
#
# **Associated manuscript:** *On the nature of chemical short-range order evolution*  
# **Author:** Guilherme Cardeal Stumpf
#
# This script generates the schematic Tkr concept used for Supplementary Figures 8 and 9. The purpose of the figure is not to fit experimental data, but to test conceptual possibilities between different diffusional regimes and CSRO evolution. In this sense, the respective points can be controlled here:  
# 1. the effect of CSRO on volume or lattice parameter, represented by the relative slope of the frozen regime;  
# 2. the position of Tkr, defined by the intersection between the extrapolated frozen and equilibrium regimes;  
# 3. the onset of significant diffusion, here represented by `T_onset_diffusion`;  
# 4. the width of the transition regime between the frozen and equilibrium (diffusion) regimes.
#
# For a Supplementary Figure 8 type plot, use `FIGURE_MODE = "SF8"`. In this mode, `T_onset_diffusion` changes with the selected Tkr state, qualitatively representing the case in which CSRO can affect diffusivity.  
# For a Supplementary Figure 9 type plot, use `FIGURE_MODE = "SF9"`. In this mode, the same `T_onset_diffusion` is imposed for all panels, qualitatively representing the case in which CSRO does not affect diffusivity.
# We encourage users to try to go beyond SF8 and SF9, and try different combinations. The idea is to evaluate all possible realistic scenarios.
#
# The script displays the figure immediately with `plt.show()` and also saves it as a PDF in the same folder as the notebook.

# 2.0 Generate Tkr schematic figure

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# =============================================================================
# User settings
# =============================================================================

# Choose the conceptual construction:
# "SF8" -> T_onset_diffusion varies with the Tkr state.
#          This represents the qualitative case in which CSRO affects diffusivity.
# "SF9" -> T_onset_diffusion is fixed for all panels.
#          This represents the qualitative case in which CSRO does not affect diffusivity.
# Name used for the saved PDFs (mode suffix and figures/ path are added automatically).
OUTPUT_BASENAME = "Tkr_concept"

# Temperature axis used only to draw the schematic curves.
Tmin, Tmax = 300.0, 1400.0
T = np.linspace(Tmin, Tmax, 900)

# Equilibrium regime, red line. This is the high-temperature reference behavior.
m_red = 2.0e-4
b_red = 1.00

# Column-dependent frozen-regime slopes.
# Lower than 1: increasing CSRO makes the structure more compact.
# Equal to 1: negligible CSRO effect on structural expansion.
# Higher than 1: increasing CSRO makes the structure expand.
col_factors = [0.5, 1.00, 1.50]

# Tkr values are generated by shifting a base value for each row.
# The three rows correspond to the relative relation between T_onset_diffusion and Tkr:
# row 1: T_onset_diffusion > Tkr
# row 2: T_onset_diffusion = Tkr
# row 3: T_onset_diffusion < Tkr
Tkr_base = 900.0
Tkr_row_shift = [-100.0, 0.0, +210.0]
Tkr_col_shift = [-0.0, 0.0, +0.0]

# For an SF8-type figure, the diffusion onset changes with the selected Tkr state.
# This qualitatively represents the case where CSRO content affects diffusivity.
row_Tdiff_offset_SF8 = [+200.0, 0.0, -300.0]

# For an SF9-type figure, the same diffusion onset is imposed for all panels.
# This qualitatively represents the case where CSRO does not affect diffusivity.
fixed_T_onset_diffusion_SF9 = 900.0

# Transition duration controls the width of the transition regime between
# the frozen segment and the equilibrium segment.
row_dT_trans = [200.0, 100.0, 200.0]

# Colors and line styles. These are kept intentionally simple because the figure is schematic.
c_blue = "#4DB6FF"
c_red = "#E53935"
c_purp = "#8E24AA"
alpha_purp = 0.35

lw_main = 3.0
lw_purp = 4.0
lw_dash = 1.2


# =============================================================================
# Helper functions
# =============================================================================

def hermite_bridge(T, T0, y0, m0, T1, y1, m1):
    """Cubic Hermite bridge matching value and slope at both ends."""
    s = (T - T0) / (T1 - T0)
    h00 =  2*s**3 - 3*s**2 + 1
    h10 =      s**3 - 2*s**2 + s
    h01 = -2*s**3 + 3*s**2
    h11 =      s**3 -   s**2
    return h00*y0 + h10*(T1 - T0)*m0 + h01*y1 + h11*(T1 - T0)*m1


def make_piecewise_curve(T, m_blue, b_blue, m_red, b_red, Tdiff, Tend):
    """
    Build the schematic curve with three regimes.

    T <= Tdiff:
        Frozen regime, blue segment.
    Tdiff < T < Tend:
        Transition regime, purple Hermite bridge.
    T >= Tend:
        Equilibrium regime, red segment.
    """
    yb = m_blue*T + b_blue
    yr = m_red*T  + b_red
    y  = np.empty_like(T, dtype=float)

    y0 = m_blue*Tdiff + b_blue
    y1 = m_red*Tend   + b_red

    left  = T <= Tdiff
    mid   = (T > Tdiff) & (T < Tend)
    right = T >= Tend

    y[left] = yb[left]
    if np.any(mid):
        y[mid] = hermite_bridge(T[mid], Tdiff, y0, m_blue, Tend, y1, m_red)
    y[right] = yr[right]

    return y, yb, yr


def vmarker_to_curve(ax, x, y_top, y_bottom, color="k", lw=0.8, ls="-", z=0):
    """Draw a vertical marker that stops at the curve instead of crossing the full panel."""
    ax.vlines(x, y_bottom, y_top, colors=color, linewidth=lw, linestyles=ls, zorder=z)


def get_T_onset_diffusion(mode, i_row, Tkr):
    """Return T_onset_diffusion according to the chosen Supplementary Figure concept."""
    if mode == "SF8":
        return Tkr + row_Tdiff_offset_SF8[i_row]
    if mode == "SF9":
        return fixed_T_onset_diffusion_SF9
    raise ValueError("FIGURE_MODE must be either 'SF8' or 'SF9'.")


# =============================================================================
# Build and plot for each mode
# =============================================================================

figures_dir = Path.cwd() / "figures"
figures_dir.mkdir(exist_ok=True)

for FIGURE_MODE in ("SF8", "SF9"):

    panel_data = {}
    y_all_min, y_all_max = +np.inf, -np.inf

    for i_row in range(3):
        for i_col in range(3):
            m_blue = m_red * col_factors[i_col]
            Tkr = Tkr_base + Tkr_row_shift[i_row] + Tkr_col_shift[i_col]
            b_blue = (m_red - m_blue) * Tkr + b_red
            Tdiff = get_T_onset_diffusion(FIGURE_MODE, i_row, Tkr)
            Tend = min(Tdiff + row_dT_trans[i_row], Tmax - 1e-6)
            y, yb, yr = make_piecewise_curve(T, m_blue, b_blue, m_red, b_red, Tdiff, Tend)
            y_all_min = min(y_all_min, np.min(np.r_[yb, yr, y]))
            y_all_max = max(y_all_max, np.max(np.r_[yb, yr, y]))
            panel_data[(i_row, i_col)] = dict(
                m_blue=m_blue, b_blue=b_blue, Tkr=Tkr,
                Tdiff=Tdiff, Tend=Tend, y=y, yb=yb, yr=yr,
            )

    pad = 0.03 * (y_all_max - y_all_min)
    ymin = y_all_min - pad
    ymax = y_all_max + pad

    fig, axs = plt.subplots(3, 3, figsize=(10, 9), sharex=True, sharey=True)

    for i_row in range(3):
        for i_col in range(3):
            ax = axs[i_row, i_col]
            d = panel_data[(i_row, i_col)]

            m_blue = d["m_blue"]
            b_blue = d["b_blue"]
            Tkr    = d["Tkr"]
            Tdiff  = d["Tdiff"]
            Tend   = d["Tend"]
            y      = d["y"]
            yb     = d["yb"]
            yr     = d["yr"]

            ax.set_xlim(Tmin, Tmax)
            ax.set_ylim(ymin, ymax)

            ax.plot(
                [Tmin, Tmax],
                [m_blue*Tmin + b_blue, m_blue*Tmax + b_blue],
                ls="--", lw=lw_dash, color=c_blue, zorder=1,
            )
            ax.plot(
                [Tmin, Tmax],
                [m_red*Tmin + b_red, m_red*Tmax + b_red],
                ls="--", lw=lw_dash, color=c_red, zorder=1,
            )

            mask_b = T <= Tdiff
            ax.plot(T[mask_b], yb[mask_b], lw=lw_main, color=c_blue, zorder=3)

            mask_p = (T > Tdiff) & (T < Tend)
            ax.plot(T[mask_p], y[mask_p], lw=lw_purp, color=c_purp, alpha=alpha_purp, zorder=4)

            mask_r = T >= Tend
            ax.plot(T[mask_r], yr[mask_r], lw=lw_main, color=c_red, zorder=3)

            y_at_Tdiff = m_blue*Tdiff + b_blue
            y_at_Tkr = m_red*Tkr + b_red

            vmarker_to_curve(ax, Tkr, y_at_Tkr, ymin, color="k", lw=0.8, ls="-", z=0)
            vmarker_to_curve(ax, Tdiff, y_at_Tdiff, ymin, color="k", lw=0.8, ls=":", z=0)

            ax.set_title("")

    axs[2, 1].set_xlabel("Temperature (K)")
    axs[1, 0].set_ylabel("Volume / lattice parameter (arb.)")

    plt.tight_layout()

    output_path = figures_dir / f"s12_{OUTPUT_BASENAME}_{FIGURE_MODE}.pdf"
    fig.savefig(output_path, bbox_inches="tight")
    print(f"Saved: {output_path}")
    plt.close(fig)
